name: summer-test
on: [push]
jobs:
  summer-test:
    runs-on: ubuntu-20.04
    steps:
      - run:  
          echo *** LOAD ***
          sudo mkdir -p /home/summer/
          sudo git clone https://github.com/docane/summer.git /home/summer/
          cd /home/summer/
          echo *** LOAD ***
          
          echo *** Install ***
          sudo apt-get update
          sudo apt install python3-pip
          
          sudo apt install python3-pytest
          echo *** install ***
          
          echo *** test ***
          pytest-3 utility.py --disable-warnings
          echo *** test ***
